# Config file for lensfit analysis

var-1:
  name: patch
  # Can handle int, float, str, list
  # More complex variable would raise errors. The below example could be
  # achieve by doing:
  value: 'list(range(1, 3))'
  # Just calling range will raise an error.
  # value: '[1, 2]'

# Name of the run
run_name: lensfit

# The directory used for the run and store the results
workspace_directory: /Users/aguinot/Documents/weaklensingvalidation_test/workspace

# If True, the processing is skiped and only the plot are done.
# For this option to work run as to be done with the same workspace_directory
# and run_name
# plot_only: True

galaxy_catalog:
  # If more than one catalog is provided they all need to have the same format
  # path: 'galaxy_catalog_1.fits'
  # path: ['galaxy_catalog_1.fits', 'galaxy_catalo_2.fits']
  path:
    type: eval
    func: "[f'galaxy_catalog_{i}.fits' for i in $patch$]"
  # If keep_cat_history == True we keep track of the objects and from which
  # catalog they come from. A variable is define internaly var_cat_history
  # that can be used to make plot per catalog (see ploting below).
  # var_cat_history can also be set manually.
  # This feature only work if more than one catalog is provided.
  keep_cat_history: True
  var_cat_history: patch

  # Type of catalog
  type: classic

  # Define columns and and link name in the catalog to internal naming
  columns:
    ra: ra
    dec: dec
    e1: e1
    e2: e2
    weights: w
    e1_psf:
      type: eval
      # Variable are first checked among internal variable (define in config
      # file) and then among the catalog columns
      func: "($PSF_Q11$ - $PSF_Q22$) / ($PSF_Q11$ + $PSF_Q22$ + 2. * sqrt($PSF_Q11$ * $PSF_Q22$ - $PSF_Q12$**2))"
    e2_psf: e2_psf
    size_psf: fwhm_psf
    mag: mag

star_catalog:
  path:
    type: eval
    func: "[f'star_catalog_{i}.fits' for i in $patch$]"
  # This part is ignored for the star catalog if a galaxy catalog is provided.
  # Everything set here will be updated based on the galaxy catalog.
  # keep_cat_history: True
  # var_cat_history: patch

  # Type of catalog
  type: classic

  columns:
    ra: ra
    dec: dec
    x: x
    y: y
    n_ccd: ccd_nb
    e1_star: e1_s
    e2_star: e2_s
    size_star: fwhm_s
    e1_psf: e1_psf
    e2_psf: e2_psf
    size_psf: fwhm_psf

